import { CalendarDays, Plus } from 'lucide-react'
import { navigate } from '../../data'

export function PageHeading({ title, subtitle, action }) { return <div className="subpage-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <button className="create-button" onClick={action}><Plus size={19} /> Create Task</button>}</div> }
function Badge({ task, status = false }) { const value = status ? task.status : task.priority; return <span className={`badge ${status ? value.toLowerCase().replace('_', '-') : `priority-${value.toLowerCase()}`}`}>{value.replace('_', ' ')}</span> }
const date = value => value ? new Date(value).toLocaleDateString('en-GB') : '—'
function Feedback({ loading, error, onRetry }) { if (loading) return <p className="muted">Loading tasks...</p>; if (error) return <p className="red-text">{error} <button className="outline-button" onClick={onRetry}>Retry</button></p>; return null }
export function BoardPage({ tasks, loading, error, onRetry, onCreate }) { const columns = [['To Do', 'todo', tasks.filter(task => task.status === 'TODO')], ['In Progress', 'progress', tasks.filter(task => task.status === 'IN_PROGRESS')], ['Done', 'done', tasks.filter(task => task.status === 'DONE')]]; return <><PageHeading title="My Tasks" subtitle="Organize and track your work across projects." action={onCreate} /><Feedback loading={loading} error={error} onRetry={onRetry} /><div className="kanban">{columns.map(([title, tone, items]) => <section className="kanban-column" key={title}><div className="kanban-title"><span className={`column-dot ${tone}`} /><h3>{title}</h3><b>{items.length}</b></div>{items.map(task => <article className="kanban-card" key={task._id}><Badge task={task} status /><h4>{task.title}</h4><p>{task.description || 'No description'}</p><div><Badge task={task} /><small><CalendarDays size={13} /> {date(task.dueDate)}</small></div></article>)}<button className="add-task-link" onClick={onCreate}><Plus size={16} /> Add task</button></section>)}</div></> }
export function ListPage({ tasks, loading, error, onRetry, onCreate }) { return <><PageHeading title="My Tasks" subtitle="View, filter, and manage all your tasks in one place." action={onCreate} /><Feedback loading={loading} error={error} onRetry={onRetry} /><article className="panel full-list"><div className="table-head"><span>Task Name</span><span>Status</span><span>Priority</span><span>Due Date</span></div>{tasks.map(task => <button className="table-row" key={task._id} onClick={() => navigate(`task/${task._id}`)}><strong>{task.title}</strong><Badge task={task} status /><Badge task={task} /><span>{date(task.dueDate)}</span></button>)}</article></> }
