import { useEffect, useState } from 'react'
import { ClipboardList, X } from 'lucide-react'
import { PageHeading } from '../components/tasks/TaskViews'
import { tasksApi } from '../services/api'

export function SettingsPage() { return <><PageHeading title="Settings" subtitle="Manage your workspace and personal preferences." /><div className="settings-layout"><aside className="settings-nav"><button className="active">Profile</button><button>Workspace</button><button>Notifications</button><button>Appearance</button></aside><section className="panel settings-card"><h3>Profile settings</h3><p className="muted">Update your personal information and account preferences.</p><div className="profile-large"><div className="user-avatar">AC</div><div><strong>Alex Chen</strong><p>alex.chen@example.com</p></div><button className="outline-button">Change photo</button></div><div className="settings-fields"><label>Full name<input value="Alex Chen" readOnly /></label><label>Email address<input value="alex.chen@example.com" readOnly /></label></div><button className="create-button save-button">Save changes</button></section></div></> }

export function DetailPage({ taskId, onClose, onChanged }) {
  const [task, setTask] = useState(null); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let active = true; setLoading(true); tasksApi.get(taskId).then(result => { if (active) { setTask(result); setForm({ ...result, dueDate: result.dueDate?.slice(0, 10) || '' }) } }).catch(err => active && setError(err.message)).finally(() => active && setLoading(false)); return () => { active = false } }, [taskId])
  const update = event => setForm({ ...form, [event.target.name]: event.target.value })
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { const result = await tasksApi.update(taskId, { title: form.title, description: form.description, priority: form.priority, dueDate: form.dueDate || undefined }); setTask(result); setForm({ ...result, dueDate: result.dueDate?.slice(0, 10) || '' }); onChanged() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const changeStatus = async event => { setSaving(true); setError(''); try { const result = await tasksApi.updateStatus(taskId, event.target.value); setTask(result); setForm({ ...result, dueDate: result.dueDate?.slice(0, 10) || '' }); onChanged() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  const remove = async () => { if (!window.confirm('Delete this task?')) return; setSaving(true); try { await tasksApi.remove(taskId); onChanged(); onClose() } catch (err) { setError(err.message); setSaving(false) } }
  if (loading) return <div className="detail-drawer"><button className="drawer-close" onClick={onClose}><X size={20} /></button><p>Loading task...</p></div>
  if (error && !form) return <div className="detail-drawer"><button className="drawer-close" onClick={onClose}><X size={20} /></button><p className="red-text">{error}</p></div>
  return <div className="detail-drawer"><button className="drawer-close" onClick={onClose}><X size={20} /></button><p className="overline">TASK DETAILS</p><form onSubmit={save}><label>Title<input name="title" value={form.title} onChange={update} required /></label><label>Description<textarea name="description" value={form.description || ''} onChange={update} rows="5" /></label><div className="modal-grid"><label>Status<select value={task.status} onChange={changeStatus} disabled={saving}><option value="TODO">To Do</option><option value="IN_PROGRESS">In Progress</option><option value="DONE">Done</option></select></label><label>Priority<select name="priority" value={form.priority} onChange={update}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label></div><label>Due Date<input type="date" name="dueDate" value={form.dueDate} onChange={update} /></label>{error && <p className="red-text">{error}</p>}<div className="modal-actions"><button type="submit" className="create-button" disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button><button type="button" className="delete-task" onClick={remove} disabled={saving}>Delete Task</button></div></form><p className="detail-meta"><small>Created</small><strong>{task.createdAt ? new Date(task.createdAt).toLocaleDateString('en-GB') : '—'}</strong></p></div>
}
export function HelpPage() { return <><PageHeading title="Help Center" subtitle="Find answers and get support." /><div className="empty-panel"><ClipboardList size={48} /><h3>How can we help?</h3><p>Documentation and support resources will appear here.</p></div></> }
